import {strict as assert} from 'node:assert';
import {createServer} from 'vite';
const server=await createServer({configFile:false,server:{middlewareMode:true,hmr:{port:24980}},optimizeDeps:{noDiscovery:true,include:[]},appType:'custom'});
try{
 const s=await server.ssrLoadModule('/src/game/state.ts'),{PUZZLES,checkPuzzle,STORY_OBJECTS}=await server.ssrLoadModule('/src/game/story.ts'),{COPY,t}=await server.ssrLoadModule('/src/game/copy.ts');
 for(const house of s.HOUSES){let save=s.reduceGame(s.newSave(),{type:'start'});assert.equal(s.reduceGame(save,{type:'solve',step:'medicine'}),save,'Skipped into rescue');save=s.reduceGame(save,{type:'solve',step:'letter'});assert.equal(s.reduceGame(save,{type:'house',house}),save,'Sorting bypass');for(let i=0;i<3;i++)save=s.reduceGame(save,{type:'answer',house});save=s.reduceGame(save,{type:'house',house});assert.equal(save.house,house);for(const step of s.STEPS.slice(2,-1)){assert.equal(save.step,step);const before=JSON.stringify(save);for(const locale of s.LOCALES){const changed=s.reduceGame(save,{type:'locale',value:locale});assert.equal(changed.step,step);assert.equal(changed.house,house);assert.deepEqual(changed.secrets,save.secrets);assert(s.parseSave(JSON.stringify(changed)));}assert.equal(JSON.stringify(save),before,'Mutated original save');save=s.reduceGame(save,{type:'solve',step});assert(s.parseSave(JSON.stringify(save)),`Invalid save after ${step}`);if(['passage','window','feast'].includes(save.step))assert.equal(save.checkpoint,s.objectivePlace(save.step));}assert.equal(save.step,'complete');const end=s.reduceGame(save,{type:'ending'});assert(end.endingRead);assert(s.parseSave(JSON.stringify(end)));}
 for(const [step,puzzle] of Object.entries(PUZZLES)){let successes=0;const max=puzzle.items.length;const enumerate=(values)=>{if(values.length===puzzle.length){if(checkPuzzle(step,values))successes++;return;}for(let i=0;i<(puzzle.kind==='dials'?4:max);i++)enumerate([...values,i]);};enumerate([]);assert.equal(successes,1,`${step} must have one solution`);assert(!checkPuzzle(step,[]));assert(!checkPuzzle(step,[...puzzle.answer,0]));assert(checkPuzzle(step,puzzle.answer));for(const suffix of ['title','body','hint','fail','done'])assert(COPY[step+'.'+suffix]);}
 for(const [key,row] of Object.entries(COPY)){assert.equal(row.length,5,key);for(const locale of s.LOCALES){const text=t(locale,key);assert(text.trim().length>0,`${key} empty in ${locale}`);assert(!/^\[.*\]$/.test(text),'Raw localization key');}}
 for(const step of s.STEPS){assert(COPY[step+'.title']);assert(COPY[step+'.body']);}for(const o of STORY_OBJECTS)assert(COPY[o.id+'.title']);
 assert.equal(s.detectLocale(['zh-Hant-HK']),'zh-TW');assert.equal(s.detectLocale(['zh-SG']),'zh-CN');assert.equal(s.detectLocale(['ja-JP']),'ja');assert.equal(s.detectLocale(['fr-FR','ko-KR']),'ko');assert.equal(s.detectLocale([]),'en');
 let save=s.reduceGame(s.newSave('en'),{type:'start'});save=s.reduceGame(save,{type:'secret',id:'wrapper'});assert.equal(s.reduceGame(save,{type:'secret',id:'wrapper'}),save,'Duplicate secret changes state');assert.equal(s.parseSave('{'),null);assert.equal(s.parseSave('x'.repeat(256001)),null);for(const invalid of [{version:2},{step:'complete'},{house:'other'},{locale:'xx'},{secrets:['wrapper','wrapper']},{revision:-1},{drafts:{'__bad':[1]}}])assert.equal(s.parseSave(JSON.stringify({...save,...invalid})),null,JSON.stringify(invalid));
 const legacy={...save};delete legacy.music;assert.equal(s.parseSave(JSON.stringify(legacy)).music,false,'Legacy saves must default to silent music');const withMusic=s.reduceGame(save,{type:'setting',music:true});assert.equal(s.parseSave(JSON.stringify(withMusic)).music,true);assert.equal(save.music,false,'Music setting mutated the previous save');assert.equal(s.parseSave(JSON.stringify({...save,music:'yes'})),null,'Invalid music type accepted');
 const data=new Map();const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};assert.equal(s.loadSave(storage,'en').status,'new');assert(s.persistSave(storage,save));assert.equal(s.loadSave(storage,'en').save.locale,'en');const next=s.reduceGame(save,{type:'solve',step:'letter'});assert(s.persistSave(storage,next));data.set(s.SAVE_KEY,'broken');const recovered=s.loadSave(storage,'zh-CN');assert.equal(recovered.status,'recovered');assert.equal(recovered.save.step,'letter');data.set(s.BACKUP_KEY,'broken too');assert.equal(s.loadSave(storage,'en').status,'corrupt');const blocked={getItem(){throw Error('denied')},setItem(){throw Error('denied')},removeItem(){throw Error('denied')}};assert.equal(s.loadSave(blocked,'ko').status,'unavailable');assert.equal(s.persistSave(blocked,save),false);
 console.log(JSON.stringify({result:'PASS',houses:4,completeRoutes:4,puzzles:Object.keys(PUZZLES).length,languages:5,localizedEntries:Object.keys(COPY).length,checks:['unique puzzle solutions','no stage skipping','manual house preference','language preserves state','valid intermediate checkpoints','idempotent secrets','corrupt and future saves rejected','backup recovery','restricted storage remains usable']},null,2));
}finally{await server.close();}
