'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Map,Volume2,VolumeX,Settings2,X,Sparkles,Move,BookOpen,WandSparkles,Languages,Check,Download,Upload,RotateCcw,Compass,Feather,Music2} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {PLACES,type PlaceId} from '@/src/world/navigation';
import type {CastleEngine,EngineState,Quality} from '@/src/world/engine';
import {registerExplorationTools} from '@/src/webmcp';
import {useGame} from '@/src/game/use-game';
import {LOCALES,SECRETS,newSave,importSave,objectivePlace,parallel,stepNumber,type Locale,type Save} from '@/src/game/state';
import {t,LANGUAGE_NAMES} from '@/src/game/copy';
import {StoryPanel} from '@/src/game/StoryPanel';
import {useMusic} from '@/src/game/use-music';
import {useOffline} from '@/src/game/use-offline';
const INITIAL:EngineState={place:'bridge',heading:0,nearPortal:false,lumos:false,mode:'overview',fps:60,actionLabel:'',message:'',stairsMoving:false};
const MAP_POINTS=[[150,288],[150,216],[150,142],[70,156],[230,156],[150,62],[242,60]];
export default function Home(){
 const mount=useRef<HTMLDivElement>(null),engine=useRef<CastleEngine|null>(null),transition=useRef<ReturnType<typeof setTimeout>|null>(null),file=useRef<HTMLInputElement>(null);
 const game=useGame(),{save,loaded,status,dispatch}=game,current=game.current;
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[state,setState]=useState(INITIAL),[panel,setPanel]=useState<'map'|'settings'|'journal'|null>(null),[story,setStory]=useState<string|null>(null),[fade,setFade]=useState(false),[hint,setHint]=useState(true),[pending,setPending]=useState<Save|'new'|null>(null),[notice,setNotice]=useState('');
 const [stick,setStick]=useState({x:0,y:0}),joystick=useRef<{id:number;x:number;y:number}|null>(null),onInteraction=useRef<(id:string)=>void>(()=>{}),lastPlace=useRef<PlaceId|null>(null);
 const music=useMusic(),offline=useOffline(),tr=(key:string)=>t(save.locale,key==='aim'&&save.step==='complete'?'chapterDone':key),overview=state.mode==='overview',inParallel=['shelter','study'].includes(state.place)&&!overview;
 useEffect(()=>{onInteraction.current=id=>{if(!current.current.started)dispatch({type:'start'});setPanel(null);setStory(id);};},[current,dispatch]);
 useEffect(()=>{let alive=true,instance:CastleEngine|null=null;import('@/src/world/engine').then(({CastleEngine})=>{if(!alive||!mount.current)return;try{instance=new CastleEngine(mount.current,s=>{if(!alive)return;setState(s);if(s.mode==='walk'&&lastPlace.current!==s.place){lastPlace.current=s.place;dispatch({type:'visit',place:s.place});}},msg=>{if(alive)setError(msg==='errorWebgl'?msg:'errorLoad');},()=>{if(alive)setReady(true);});instance.onInteraction=id=>onInteraction.current(id);engine.current=instance;}catch(e){console.error(e);setError('errorWebgl');}}).catch(()=>setError('errorLoad'));return()=>{alive=false;if(transition.current)clearTimeout(transition.current);instance?.dispose();engine.current=null;};},[dispatch]);
 useEffect(()=>{if(!ready||!loaded)return;engine.current?.setGame(save);if(engine.current&&engine.current.quality!==save.quality)engine.current.setQuality(save.quality);document.documentElement.lang=save.locale;document.title=t(save.locale,'title')+' · '+t(save.locale,'castle');},[ready,loaded,save]);
 useEffect(()=>{const paused=!!panel||!!story||!!pending||status==='conflict';engine.current?.setPaused(paused);if(paused){joystick.current=null;const frame=requestAnimationFrame(()=>setStick({x:0,y:0}));return()=>cancelAnimationFrame(frame);}},[panel,story,pending,status,ready]);
 useEffect(()=>{const clear=()=>{joystick.current=null;setStick({x:0,y:0});};window.addEventListener('blur',clear);window.addEventListener('resize',clear);return()=>{window.removeEventListener('blur',clear);window.removeEventListener('resize',clear);};},[]);
 useEffect(()=>{if(ready&&engine.current)return registerExplorationTools(engine.current,()=>{setPanel(null);setStory(null);});},[ready]);
 useEffect(()=>{if(overview)return;const timer=setTimeout(()=>setHint(false),14000);return()=>clearTimeout(timer);},[overview]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.repeat||/INPUT|SELECT|TEXTAREA/.test((e.target as HTMLElement)?.tagName))return;if(e.key.toLowerCase()==='m'&&!story&&!pending){e.preventDefault();setPanel(v=>v==='map'?null:'map');}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[story,pending]);
 const travel=(id:PlaceId)=>{if(!engine.current)return;setPanel(null);setStory(null);setFade(true);if(transition.current)clearTimeout(transition.current);transition.current=setTimeout(()=>{engine.current?.enter(id);engine.current?.setPaused(false);setFade(false);setHint(true);},320);};
 const start=()=>{dispatch({type:'start'});if(current.current.music)music.setEnabled(true);engine.current?.setSound(current.current.sound);travel(current.current.checkpoint);};
 const returnOverview=()=>{setPanel(null);setStory(null);engine.current?.overview();};
 const toggleSound=()=>{const value=!save.sound;dispatch({type:'setting',sound:value});engine.current?.setSound(value);};
 const advanceStory=()=>{const old=story;setStory(null);if(old==='stars')travel('shelter');else if(old==='medicine')travel('study');else if(old==='cabinet')travel('hall');else if(old==='feast')setStory('complete');};
 const toggleMusic=()=>{const enabled=!music.playing;dispatch({type:'setting',music:enabled});music.setEnabled(enabled);};
 const onSpeak=useCallback((seconds:number)=>engine.current?.setHatSpeech(seconds),[]);
 useEffect(()=>{engine.current?.setStoryFocus(story==='sorting'?'sorting':null);},[story,ready]);
 const changeLanguage=(locale:Locale)=>dispatch({type:'locale',value:locale});
 const languageSelect=<label className="language-select"><Languages size={17}/><select aria-label={tr('language')} value={save.locale} onChange={e=>changeLanguage(e.target.value as Locale)}>{LOCALES.map(l=><option key={l} value={l}>{LANGUAGE_NAMES[l]}</option>)}</select></label>;
 const joystickMove=(e:React.PointerEvent)=>{if(joystick.current?.id!==e.pointerId)return;const dx=e.clientX-joystick.current.x,dy=e.clientY-joystick.current.y,factor=Math.min(1,39/Math.max(1,Math.hypot(dx,dy))),x=dx*factor,y=dy*factor;setStick({x,y});if(engine.current)engine.current.move={x:x/39,y:y/39};};
 const joystickEnd=()=>{joystick.current=null;setStick({x:0,y:0});if(engine.current)engine.current.move={x:0,y:0};};
 const exportProgress=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(current.current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='hogwarts-promises-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const readFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setNotice('');if(f.size>256_000){setNotice('importError');return;}try{const incoming=importSave(await f.text(),current.current.locale);if(!incoming){setNotice('importError');return;}setPending(incoming);}catch{setNotice('importError');}};
 const confirmReplace=()=>{if(!pending)return;const next=pending==='new'?{...newSave(save.locale),quality:save.quality,sound:save.sound,music:save.music}:pending;game.replace(next);music.setEnabled(next.music);lastPlace.current=null;setNotice('');setPending(null);setStory(null);setPanel(null);engine.current?.overview();};
 return <main lang={save.locale} data-step={save.step} data-fps={state.fps} data-place={state.place} className={`experience story-experience ${overview?'is-overview':'is-walking'} ${ready?'is-ready':''} ${inParallel?'is-parallel':''} ${story==='sorting'?'is-sorting':''}`}>
  <div className="world-canvas" ref={mount}/><div className="cinema-shade" aria-hidden="true"/><div className="fine-grain" aria-hidden="true"/>
  <header className="topbar"><button className="brand" aria-label={tr('overview')} onClick={returnOverview}><span className="brand-seal">H<span>✧</span></span><span className="brand-wordmark">HOGWARTS<small>{tr('title')}</small></span></button><div className="top-location">{inParallel?tr('parallel'):overview?tr('edition'):tr(state.place)}</div><nav className="top-tools" aria-label={tr('settings')}>{languageSelect}<button className={`icon-button music-control ${music.playing?'active':''}`} aria-label={tr(music.playing?'musicMute':'musicPlay')} aria-pressed={music.playing} onClick={toggleMusic}><Music2/>{!music.playing&&<i className="music-slash"/>}</button><button className={`icon-button ${save.sound?'active':''}`} aria-label={tr(save.sound?'soundOff':'soundOn')} onClick={toggleSound}>{save.sound?<Volume2/>:<VolumeX/>}</button><button className="icon-button" aria-label={tr('settings')} onClick={()=>setPanel('settings')}><Settings2/></button></nav></header>
  {overview?<><section className="arrival"><div className="eyebrow"><span/>{tr('edition')}</div><h1>{tr('castle')}<span>{tr('title')}</span></h1><p>{tr('subtitle')}</p><div className="arrival-actions"><button className="enter-button" disabled={!ready||!loaded} onClick={start}><WandSparkles size={18}/>{tr(ready?save.started?'continue':'start':'loading')}<ArrowRight size={20}/></button><button className="text-button" disabled={!ready} onClick={()=>setPanel('map')}>{tr('explore')}<ArrowUpRight size={16}/></button></div><div className="arrival-note">{tr('noAI')}</div></section><aside className="chapter-preview"><span className="chapter-numeral">I</span><div><small>{tr('chapter')}</small><h2>{tr('title')}</h2><p>{tr('subtitle')}</p>{save.started&&<button className="text-button" onClick={()=>setPanel('journal')}>{tr('journal')}<ArrowRight size={15}/></button>}</div></aside><footer className="overview-footer"><span>✧ {tr(offline==='ready'?'offline':offline==='pending'?'caching':'localOnly')}</span><span>{tr('fanwork')}</span></footer></>:<>
   <div className="walk-location"><span>{inParallel?tr('parallel'):save.house?tr(save.house):tr('castle')}</span><h2>{tr(state.place)}</h2></div>
   <button className="objective-tracker" onClick={()=>setPanel('journal')}><span className="objective-symbol">✦</span><span><small>{tr('aim')}</small><strong>{tr(save.step+'.title')}</strong></span>{state.objectiveDistance!==undefined&&<em>{state.objectiveDistance} m</em>}<BookOpen size={17}/></button>
   <div className="crosshair" aria-hidden="true"/>
   {hint&&<div className="walk-hint">{tr('controls')}<button aria-label={tr('close')} onClick={()=>setHint(false)}><X size={14}/></button></div>}
   {state.actionLabel&&<button className="portal-action" disabled={state.stairsMoving&&state.place==='stairs'&&!state.actionId} onClick={()=>engine.current?.interact()}><Sparkles size={17}/>{state.stairsMoving&&!state.actionId?tr('stairsMoving'):state.actionLabel}</button>}
   {state.message&&<output className="scene-message">{state.message}</output>}
   <fieldset className="movement-pad" aria-label={tr('joystick')} onPointerDown={e=>{if(joystick.current)return;e.currentTarget.setPointerCapture(e.pointerId);const rect=e.currentTarget.getBoundingClientRect();joystick.current={id:e.pointerId,x:rect.left+rect.width/2,y:rect.top+rect.height/2};joystickMove(e);}} onPointerMove={joystickMove} onPointerUp={joystickEnd} onPointerCancel={joystickEnd} onLostPointerCapture={joystickEnd}><span className="stick-n">⌃</span><span className="stick-e">›</span><span className="stick-w">‹</span><span className="stick-s">⌄</span><div className="stick-center" style={{transform:`translate(${stick.x}px,${stick.y}px)`}}><Move size={17}/></div></fieldset>
   <div className="spell-controls"><button className={`lumos-button ${state.lumos?'lit':''}`} aria-label={tr(state.lumos?'nox':'lumos')} aria-pressed={state.lumos} onClick={()=>engine.current?.toggleLumos()}><Sparkles size={21}/><span>{tr(state.lumos?'nox':'lumos')}</span></button><button className="cast-button" aria-label={tr('cast')} onClick={()=>engine.current?.cast()}><WandSparkles size={24}/><span>{tr('cast')}</span></button></div>
   <footer className="walk-footer"><button onClick={()=>setPanel('map')}><Map size={17}/><span>{tr('map')}</span></button><button onClick={()=>setPanel('journal')}><BookOpen size={17}/><span>{tr('journal')}</span></button><span className="save-indicator"><span className="live-dot"/>{tr(status==='unavailable'||status==='corrupt'?'unsaved':'saved')}</span></footer>
  </>}
  {!ready&&!error&&<div className="loading-screen"><div className="loading-emblem">H</div><span>{tr('loading')}</span><div className="loading-line"/><small>{tr('loadingNote')}</small></div>}
  <div className={`travel-fade ${fade?'visible':''}`} aria-hidden="true"/>
  {(error||status==='conflict')&&<div className="error-banner" role="alert"><p>{tr(error||'conflict')}</p><button onClick={()=>window.location.reload()}>{tr('reload')}</button>{status==='conflict'&&<button onClick={exportProgress}>{tr('export')}</button>}</div>}
  {loaded&&(status==='corrupt'||status==='unavailable')&&!panel&&<output className="error-banner save-warning"><p>{tr(status==='corrupt'?'corrupt':'saveError')}</p><button onClick={()=>setPanel('settings')}>{tr('save')}</button></output>}
  <Dialog open={panel==='map'} onOpenChange={open=>!open&&setPanel(null)}><DialogContent className="castle-dialog map-dialog" showCloseButton={false}><div className="dialog-heading"><div><div className="eyebrow">✧ {tr('castle')}</div><DialogTitle className="dialog-title">{tr('map')}</DialogTitle></div><button className="icon-button" aria-label={tr('close')} onClick={()=>setPanel(null)}><X/></button></div><DialogDescription className="dialog-description">{tr('mapDesc')}</DialogDescription><div className="map-layout"><div className="map-drawing"><svg viewBox="0 0 300 330" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1"><path d="M130 300V244H110V197H35V107H111V36H189V107H265V197H190V244H170V300Z"/><path d="M118 184V97H182V184ZM48 118H101V185H48ZM199 118H252V185H199ZM122 49H178V85H122ZM117 218H184M150 186V239M140 250V296M160 250V296"/><path d="M126 64L174 74M126 74L174 56M131 102V174M145 102V174M157 102V174M171 102V174" opacity=".5"/></g>{PLACES.map((p,i)=><g key={p.id} className={`map-marker ${p.id===state.place?'current':''}`} transform={`translate(${MAP_POINTS[i].join(',')})`}><circle r="12"/><text y="4">{i+1}</text></g>)}</svg></div><div className="place-list">{PLACES.map((p,i)=><button className={`place-option ${state.place===p.id?'selected':''}`} key={p.id} onClick={()=>travel(p.id)}><span className="dest-number">0{i+1}</span><span><strong>{tr(p.id)}{save.visited.includes(p.id)&&<Check size={12}/>}</strong>{objectivePlace(save.step)===p.id&&<small>{tr('aim')}</small>}</span><ArrowUpRight size={16}/></button>)}</div></div><div className="map-bottom"><span><Compass size={16}/>{tr('visited')} {save.visited.filter(p=>PLACES.some(x=>x.id===p)).length} / 7</span>{parallel(save.step)&&<button className="text-button" onClick={()=>travel(objectivePlace(save.step))}>{tr('resumeChapter')}<ArrowRight size={15}/></button>}</div></DialogContent></Dialog>
  <Dialog open={panel==='journal'} onOpenChange={open=>!open&&setPanel(null)}><DialogContent className="castle-dialog journal-dialog" showCloseButton={false}><div className="dialog-heading"><div><div className="eyebrow">✧ {tr('title')}</div><DialogTitle className="dialog-title">{tr('journal')}</DialogTitle></div><button className="icon-button" aria-label={tr('close')} onClick={()=>setPanel(null)}><X/></button></div><DialogDescription className="dialog-description">{save.house?tr(save.house):tr('edition')}</DialogDescription><div className="journal-current"><div className="chapter-counter">{String(Math.min(12,stepNumber(save.step)+1)).padStart(2,'0')}<span>/ 12</span></div><div><small>{tr('aim')}</small><h3>{tr(save.step+'.title')}</h3><p>{tr('nearby')}</p><button className="text-button" onClick={()=>travel(objectivePlace(save.step))}>{tr('guide')}<ArrowRight size={17}/></button></div></div><div className="chapter-progress" aria-label={tr('chapter')}>{Array.from({length:12},(_,i)=><i key={i} className={i<stepNumber(save.step)?'done':i===stepNumber(save.step)?'now':''}/>)}</div><h3 className="journal-subheading">{tr('secrets')} <small>{save.secrets.length} / 5</small></h3><div className="secret-list">{SECRETS.map((s,i)=><button key={s} disabled={!save.secrets.includes(s)} onClick={()=>{setPanel(null);setStory(s);}}><span>{save.secrets.includes(s)?'✧':String(i+1).padStart(2,'0')}</span><div><strong>{tr(save.secrets.includes(s)?s+'.title':'notFound')}</strong><small>{tr(['bridge','courtyard','stairs','stairs','library'][i])}</small></div>{save.secrets.includes(s)&&<Check size={15}/>}</button>)}</div>{stepNumber(save.step)>=11&&<button className="study-revisit" onClick={()=>travel('study')}><Feather size={18}/>{tr('returnStudy')}<ArrowUpRight size={17}/></button>}{inParallel&&<button className="quiet-action" onClick={()=>travel('hall')}>{tr('returnStory')}</button>}</DialogContent></Dialog>
  <Dialog open={panel==='settings'} onOpenChange={open=>!open&&setPanel(null)}><DialogContent className="castle-dialog settings-dialog" showCloseButton={false}><div className="dialog-heading"><DialogTitle className="dialog-title">{tr('settings')}</DialogTitle><button className="icon-button" aria-label={tr('close')} onClick={()=>setPanel(null)}><X/></button></div><DialogDescription className="dialog-description">{tr('noAI')}</DialogDescription><div className="preference-row"><div><label htmlFor="settings-language">{tr('language')}</label><small>{tr('languageDesc')}</small></div><select id="settings-language" value={save.locale} onChange={e=>changeLanguage(e.target.value as Locale)}>{LOCALES.map(l=><option key={l} value={l}>{LANGUAGE_NAMES[l]}</option>)}</select></div><div className="preference-row"><div><span>{tr('sound')}</span><small>{tr('soundDesc')}</small></div><button className={`sound-toggle ${save.sound?'on':''}`} aria-label={tr('sound')} role="switch" aria-checked={save.sound} onClick={toggleSound}><span/></button></div><div className="preference-row"><div><span>{tr('music')}</span><small>{tr('musicDesc')}</small>{music.failed&&<small role="alert">{tr('musicRetry')}</small>}</div><button className={`sound-toggle ${music.playing?'on':''}`} aria-label={tr('music')} role="switch" aria-checked={music.playing} onClick={toggleMusic}><span/></button></div><div className="quality-setting"><span>{tr('quality')}</span><div className="quality-buttons">{(['auto','high','low'] as Quality[]).map(q=><button key={q} aria-pressed={save.quality===q} className={save.quality===q?'selected':''} onClick={()=>dispatch({type:'setting',quality:q})}>{tr(q)}</button>)}</div><p>{tr('qualityDesc')}</p></div><div className="save-setting"><strong>{tr('save')}</strong><p>{tr(status==='unavailable'?'saveError':status==='corrupt'?'corrupt':status==='recovered'?'recovered':'localOnly')}</p><div className="save-buttons"><button onClick={exportProgress}><Download size={17}/>{tr('export')}</button><button onClick={()=>file.current?.click()}><Upload size={17}/>{tr('import')}</button></div><input hidden ref={file} type="file" accept="application/json,.json" onChange={readFile}/>{notice&&<p role="alert">{tr(notice)}</p>}<p className="offline-note">{tr(offline==='ready'?'offline':offline==='pending'?'caching':'onlineOnly')}</p><button className="quiet-action restart-action" onClick={()=>setPending('new')}><RotateCcw size={15}/>{tr('newGame')}</button></div><p className="fan-note">{tr('fanwork')}</p></DialogContent></Dialog>
  {story&&<StoryPanel onSpeak={onSpeak} key={story} id={story} save={save} dispatch={dispatch} onClose={()=>setStory(null)} onAdvance={advanceStory}/>}
  <Dialog open={!!pending} onOpenChange={open=>!open&&setPending(null)}><DialogContent className="castle-dialog settings-dialog" showCloseButton={false}><DialogTitle className="dialog-title">{tr(pending==='new'?'newGame':'import')}</DialogTitle><DialogDescription className="dialog-description">{tr(pending==='new'?'newConfirm':'importConfirm')}</DialogDescription><div className="confirm-actions"><button className="quiet-action" onClick={()=>setPending(null)}>{tr('back')}</button><button className="story-primary" onClick={confirmReplace}>{tr('confirm')}</button></div></DialogContent></Dialog>
 </main>;
}
