import {chromium,executablePath} from './qa-runtime.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {strict as assert} from 'node:assert';
const seed=JSON.parse(await readFile('outputs/qa-singleplayer/completed-save.json','utf8'));
const browser=await chromium.launch({headless:true,executablePath,args:['--use-angle=metal']});const results=[],errors=[];await mkdir('outputs/qa-polish',{recursive:true});
async function contextFor(data,viewport={width:1440,height:960}){const context=await browser.newContext({viewport,locale:'zh-CN'});await context.addInitScript(s=>{if(!localStorage.getItem('hogwarts-unkept-promises-v1'))localStorage.setItem('hogwarts-unkept-promises-v1',JSON.stringify(s));window.__qaAudio=[];const Original=window.Audio;window.Audio=function(...args){const a=new Original(...args);window.__qaAudio.push(a);return a;};window.__qaTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.__qaTools[t.name]=t;}},configurable:true});},{...seed,...data});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4175/');await page.locator('.experience.is-ready').waitFor({timeout:60000});return {context,page};}
const shot=(page,name)=>page.screenshot({path:`outputs/qa-polish/${name}.png`});
try{
 const {context,page}=await contextFor({step:'letter',house:null,sorting:[],started:false,endingRead:false,checkpoint:'bridge',music:false});
 assert.equal(await page.evaluate(()=>window.__qaAudio.length),0,'Music started without a gesture');await page.getByRole('button',{name:'播放背景音乐',exact:true}).click();await page.waitForFunction(()=>window.__qaAudio.some(a=>!a.paused&&a.currentTime>.1));await page.getByRole('button',{name:'静音背景音乐',exact:true}).click();assert(await page.evaluate(()=>window.__qaAudio.every(a=>a.paused)));
 await page.getByRole('button',{name:'播放背景音乐',exact:true}).click();await page.waitForFunction(()=>window.__qaAudio[0].currentTime>.2&&!window.__qaAudio[0].paused);assert.equal(await page.evaluate(()=>window.__qaAudio.length),1,'Duplicate audio streams');await page.getByRole('button',{name:'静音背景音乐',exact:true}).click();results.push({musicUserGesture:true,actualAudioClockAdvances:true,muteAndResume:true,singleAudioInstance:true});
 await page.locator('.enter-button').click();await page.waitForTimeout(700);await page.keyboard.down('w');await page.waitForTimeout(1000);await page.keyboard.up('w');await page.waitForTimeout(450);await page.locator('.portal-action').click();await page.waitForTimeout(300);await shot(page,'envelope-sealed');await page.getByRole('button',{name:'拆开信封',exact:true}).first().click();await page.waitForTimeout(350);await shot(page,'envelope-opening');await page.locator('.invitation-dialog.is-reading').waitFor();await page.waitForTimeout(550);await shot(page,'letter-open');await page.getByRole('button',{name:'关闭',exact:true}).click();assert.equal(await page.locator('main').getAttribute('data-step'),'letter','Opening alone completed the quest');results.push({envelopeAnimation:true,readBeforeProgress:true});await context.close();
 for(const locale of ['zh-CN','zh-TW','en','ja','ko']){
  const {context,page}=await contextFor({locale,step:'sorting',house:null,sorting:[],started:true,endingRead:false,checkpoint:'hall'},{width:390,height:844});await page.locator('.enter-button').click();await page.waitForTimeout(700);await page.keyboard.down('w');await page.waitForTimeout(6380);await page.keyboard.up('w');await page.waitForTimeout(450);const before=await page.evaluate(()=>window.__qaTools.read_castle_exploration.execute());await page.locator('.portal-action').click();await page.locator('.sorting-dialog').waitFor();await page.waitForTimeout(1000);await shot(page,`hat-${locale}-portrait`);
  const rect=await page.locator('.sorting-dialog').boundingBox();assert(rect.x>=0&&rect.y>=350&&rect.x+rect.width<=391&&rect.y+rect.height<=845);
  await page.locator('.sorting-questions .story-options button').nth(2).click();await page.setViewportSize({width:844,height:390});await page.waitForTimeout(650);await shot(page,`hat-${locale}-landscape`);const landscape=await page.locator('.sorting-dialog').boundingBox();assert(landscape.x>400&&landscape.y>=0&&landscape.y+landscape.height<=391);
  await page.locator('.story-close').click();await page.waitForTimeout(350);const after=await page.evaluate(()=>window.__qaTools.read_castle_exploration.execute());assert(Math.hypot(...before.position.map((n,i)=>n-after.position[i]))<.05,'Focus did not restore position');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('hogwarts-unkept-promises-v1')).sorting.length),1);results.push({locale,liveHatPortrait:true,liveHatLandscape:true,focusRestoresPosition:true});await context.close();console.log('PASS ceremony',locale);
 }
 assert.deepEqual(errors,[]);console.log('PASS BGM, envelope, five-language live ceremony');
}catch(error){console.error(error);process.exitCode=1;}finally{await writeFile('outputs/qa-polish/results.json',JSON.stringify({results,errors},null,2));await browser.close();}
